import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

/**
 * US-T14's throttle: the read-increment-compare behind `POST /logEvent`.
 *
 * It is one `internalMutation` for a load-bearing reason. A Convex mutation is a single
 * serializable transaction, so reading a counter, bumping it, and comparing it to the ceiling all
 * happen atomically - two concurrent requests for the same key cannot both read the same pre-bump
 * count and both slip under the ceiling. The HTTP action calls this **before** `logEvent`, and
 * inserts a row only when it answers `allowed: true`, so a throttled request never reaches the
 * `events` table. It is internal for the same reason `logEvent` is: the public HTTP action is the
 * sink's only entry point.
 *
 * **Two keys, two ceilings.** The primary key is the per-install identifier the client carries in
 * the request body; the backstop is the coarse source IP. They get different ceilings on purpose:
 * shared egress (corporate and carrier NAT) puts many legitimate installs behind one IP, so the IP
 * ceiling sits well above the per-install one, high enough not to throttle a crowd but low enough
 * to catch one source flooding fresh identifiers. The shared secret is deliberately **not** a key -
 * every client build embeds the same secret, so keying on it would collapse the whole user base
 * into one bucket and throttle everyone while stopping nothing.
 *
 * **What this stops, and what it does not.** The per-install identifier is generated by the client
 * and freely rotatable, so a determined abuser can mint unlimited fresh ones and stay under the
 * per-install ceiling forever; the IP backstop is the only key the client does not choose, and even
 * that is weakened by proxies and shared egress. So this raises the cost of a casual or accidental
 * flood - it does not defeat a determined attacker. That honest limit is the same one the shared
 * secret carries, and both are documented in `convex/README.md`.
 *
 * **Bounded and ephemeral.** Baking the window into `bucketKey` makes each window its own row, so a
 * key that has gone quiet leaves a row belonging to a past window rather than a live counter. A
 * scheduled cron (`convex/crons.ts`, ~once a minute) reclaims those expired rows in bounded batches
 * via `reclaimExpired`, so the table cannot grow without limit as abusers churn through identifiers.
 * That reclamation runs **off** the request path on purpose: the hot path does only point operations
 * on the caller's own bucket, so concurrent requests from different installs never contend on a
 * shared range under Convex's optimistic concurrency. That is the "window-bucketed keys that are
 * cleaned up" shape FR-6 permits.
 */

/**
 * The throttle window and the two ceilings. Exported so the boundary suite reasons about the exact
 * numbers rather than hard-coding copies of them, and so `convex/README.md` cites one source.
 *
 * A real client emits on the order of ten events in a busy minute (app entry, onboarding, one
 * session's lifecycle), so `MAX_EVENTS_PER_INSTALL_PER_WINDOW` sits several times above that -
 * generous headroom for a legitimate burst, far below a flood. The IP ceiling is an order of
 * magnitude higher because it must clear a crowd behind one NAT.
 */
export const RATE_LIMIT_WINDOW_MS = 60_000;
export const MAX_EVENTS_PER_INSTALL_PER_WINDOW = 60;
export const MAX_EVENTS_PER_IP_PER_WINDOW = 600;

/**
 * How many expired rows one `reclaimExpired` tick may delete. A bound rather than "all of them" so a
 * single cron run does constant work regardless of how large the backlog has grown: a large backlog
 * is drained over several ticks, bounded per run by design.
 *
 * Sized to comfortably outpace one flooding IP at the ~once-a-minute cron cadence: a single source is
 * capped at `MAX_EVENTS_PER_IP_PER_WINDOW` (600) fresh install rows per window, so at most ~600 rows
 * per minute become reclaimable once that window rolls, and 2000 per tick drains that faster than it
 * accrues while staying well within a Convex mutation's per-transaction write budget.
 */
export const RECLAIM_BATCH = 2000;

type LimitedBy = "install" | "ip";

/**
 * Bump one key's counter for the current window and report whether it is now over its ceiling.
 *
 * The current window's row is found by its exact `bucketKey`, so this is an indexed point lookup,
 * not a scan. A rejected request still increments - it consumed an attempt - so an attacker sitting
 * exactly at the ceiling does not get a free request every window by being rejected.
 */
async function bump(
  ctx: { db: any },
  scope: LimitedBy,
  identity: string,
  windowStart: number,
  ceiling: number,
): Promise<boolean> {
  const bucketKey = `${scope}:${identity}:${windowStart}`;
  const existing = await ctx.db
    .query("rateLimits")
    .withIndex("by_bucketKey", (q: any) => q.eq("bucketKey", bucketKey))
    .unique();

  if (existing === null) {
    await ctx.db.insert("rateLimits", { bucketKey, windowStart, count: 1 });
    return 1 > ceiling;
  }

  const next = existing.count + 1;
  await ctx.db.patch(existing._id, { count: next });
  return next > ceiling;
}

export const checkAndBump = internalMutation({
  args: {
    /** The per-install identifier from the request body - the primary key. */
    installId: v.string(),
    /** The coarse source IP, or `null` when the edge gave the action no usable client address. */
    sourceIp: v.union(v.string(), v.null()),
    /**
     * The server's receive time in ms, stamped by the HTTP action so both keys share one window
     * and so the window is anchored to server time rather than the client-supplied (forgeable)
     * `clientTs`. Passed in - rather than read here - so the boundary suite can drive a window roll
     * deterministically by calling this mutation directly with two timestamps.
     */
    nowMs: v.number(),
  },
  returns: v.object({
    allowed: v.boolean(),
    limitedBy: v.union(v.literal("install"), v.literal("ip"), v.null()),
  }),
  handler: async (ctx, { installId, sourceIp, nowMs }) => {
    const windowStart = nowMs - (nowMs % RATE_LIMIT_WINDOW_MS);

    // Bump both keys before evaluating either, so a request that trips the IP backstop still counts
    // against the install key it also carried - the two counters do not race each other, and an
    // over-ceiling request is fully accounted for on both.
    const installOver = await bump(
      ctx,
      "install",
      installId,
      windowStart,
      MAX_EVENTS_PER_INSTALL_PER_WINDOW,
    );
    const ipOver =
      sourceIp === null
        ? false
        : await bump(ctx, "ip", sourceIp, windowStart, MAX_EVENTS_PER_IP_PER_WINDOW);

    // The hot path does only point operations on the caller's own bucket(s) - the install bump and
    // the optional IP bump above - and never scans or deletes across the table. Reclaiming expired
    // rows is a scheduled cron's job (`reclaimExpired`), off the request path, so two requests from
    // different installs never contend on a shared range under Convex's optimistic concurrency.

    // The install key is reported first when both trip, since it is the more specific of the two.
    const limitedBy: LimitedBy | null = installOver ? "install" : ipOver ? "ip" : null;
    return { allowed: limitedBy === null, limitedBy };
  },
});

/**
 * Reclaim expired rate-limit rows in a bounded batch. Scheduled by `convex/crons.ts` to run roughly
 * once a minute, off the request path, so the throttle's hot path never scans or deletes across the
 * shared table and concurrent requests from different installs cannot contend.
 *
 * A row is expired once its window has fully rolled: `windowStart < currentWindowStart`. `Date.now()`
 * is read here rather than injected because this is not the engine and there is no caller to thread a
 * clock through - a Convex mutation may read the wall clock (the `logEvent` mutation already does),
 * and reclamation is best-effort maintenance of the ephemeral helper table, not a decision anything
 * depends on. At most `RECLAIM_BATCH` rows are deleted per tick, so a large backlog drains over
 * several ticks rather than turning one run into an unbounded scan.
 */
export const reclaimExpired = internalMutation({
  args: {},
  returns: v.object({ deleted: v.number() }),
  handler: async (ctx) => {
    const now = Date.now();
    const currentWindowStart = now - (now % RATE_LIMIT_WINDOW_MS);
    const expired = await ctx.db
      .query("rateLimits")
      .withIndex("by_windowStart", (q: any) => q.lt("windowStart", currentWindowStart))
      .take(RECLAIM_BATCH);
    for (const row of expired) {
      await ctx.db.delete(row._id);
    }
    return { deleted: expired.length };
  },
});
