#!/usr/bin/env python3
"""Rep Today creative loop - dry-run implementation.

Python 3 standard library only. No network. No credentials. Nothing here
can publish anywhere: the publish adapter is stubbed and disabled by design,
and this tool has never been run against any real account.

Commands:
    python3 creative_loop.py generate    # angle bank -> briefs + creative log
    python3 creative_loop.py qa          # brand-rules lint of every brief
    python3 creative_loop.py scoreboard  # angle table with honest null results
    python3 creative_loop.py publish     # refuses, by design (NotImplementedError)
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ANGLES_PATH = os.path.join(HERE, "angles.seed.json")
RULES_PATH = os.path.join(HERE, "brand-rules.json")
OUT_DIR = os.path.join(HERE, "out")
LOG_PATH = os.path.join(OUT_DIR, "creative-log.json")

BRIEF_TEMPLATE = """# Creative brief: {angle_id}

Status: draft.
This brief was generated by the dry-run creative loop.
It has never been published and has never touched a real ad account.

## Pain state

{pain_state}
Verbatim source quote: "{verbatim_quote}"
Source: {pain_source_url}

## Hypothesis

{hypothesis}

## Hook

{hook}

## Format

{format} ({platform})

## Pre-registered success signal

{preregistered_success_signal}

## Kill criterion

{kill_criterion}

## Disclosure

Screen images simulated. App is pre-release.
"""


def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def load_angles():
    return load_json(ANGLES_PATH)["angles"]


# ---------------------------------------------------------------- generate


def cmd_generate():
    angles = load_angles()
    os.makedirs(OUT_DIR, exist_ok=True)
    log_entries = []
    for angle in angles:
        brief_name = "brief-{}.md".format(angle["angle_id"])
        brief_path = os.path.join(OUT_DIR, brief_name)
        with open(brief_path, "w", encoding="utf-8") as f:
            f.write(BRIEF_TEMPLATE.format(**angle))
        log_entries.append(
            {
                "angle_id": angle["angle_id"],
                "pain_source_url": angle["pain_source_url"],
                "hypothesis": angle["hypothesis"],
                "hook": angle["hook"],
                "format": angle["format"],
                "platform": angle["platform"],
                "brand_qa": {"pass": None, "notes": "not yet run"},
                "status": "draft",
                "preregistered_success_signal": angle["preregistered_success_signal"],
                "kill_criterion": angle["kill_criterion"],
                "results": {
                    "published_at": None,
                    "impressions": None,
                    "signal_value": None,
                    "skan_postbacks": None,
                    "campaign_level_cost": None,
                    "measured_window": None,
                },
                "brief_file": os.path.join("out", brief_name),
            }
        )
        print("wrote {}".format(os.path.relpath(brief_path, HERE)))
    with open(LOG_PATH, "w", encoding="utf-8") as f:
        json.dump({"never_published": True, "entries": log_entries}, f, indent=2)
        f.write("\n")
    print("wrote {} ({} angles, all results null)".format(
        os.path.relpath(LOG_PATH, HERE), len(log_entries)))


# ---------------------------------------------------------------- qa


def section(text, name):
    """Return the body of a '## <name>' markdown section, or None."""
    m = re.search(
        r"^## {}\n(.*?)(?=^## |\Z)".format(re.escape(name)),
        text,
        re.M | re.S,
    )
    return m.group(1).strip() if m else None


def qa_brief(text, rules):
    """Lint one brief. Returns a list of failure notes (empty = pass)."""
    notes = []

    for ch in rules["banned_characters_anywhere"]:
        if ch in text:
            notes.append("banned character {!r} found in brief".format(ch))

    for name in rules["required_sections"]:
        if section(text, name) is None:
            notes.append("missing required section: {}".format(name))

    pain = section(text, "Pain state") or ""
    if not pain:
        notes.append("pain state is empty: the pain must be named")
    if rules["pain_source_url_must_start_with"] not in pain:
        notes.append("no {} source URL in pain state".format(
            rules["pain_source_url_must_start_with"]))

    disclosure = section(text, "Disclosure") or ""
    if rules["required_disclosure"] not in disclosure:
        notes.append("missing disclosure line: {!r}".format(
            rules["required_disclosure"]))

    hook = section(text, "Hook") or ""
    hook_line = hook.splitlines()[0].strip() if hook else ""
    if not hook_line:
        notes.append("hook is empty")
    else:
        words = hook_line.split()
        if len(words) > rules["hook_max_words"]:
            notes.append("hook is {} words (max {})".format(
                len(words), rules["hook_max_words"]))
        if rules["hook_must_not_be_question"] and "?" in hook_line:
            notes.append("hook asks a question (brand: ads never interrogate)")
        lowered = hook_line.lower()
        for word in rules["banned_words_in_hook"]:
            if re.search(r"\b{}(s|es)?\b".format(re.escape(word)), lowered):
                notes.append("banned word in hook: {!r}".format(word))
        for phrase in rules["banned_social_proof_in_hook"]:
            if phrase in lowered:
                notes.append("social-proof language in hook: {!r}".format(phrase))
        if rules["no_emoji_in_hook"]:
            for c in hook_line:
                if ord(c) > 0x2100:
                    notes.append("non-text symbol in hook: {!r}".format(c))
        if rules["no_all_caps_words_in_hook"]:
            for w in words:
                bare = w.strip(".,!:;\"'()")
                if (len(bare) > 1 and bare.isupper()
                        and bare not in rules["all_caps_allowlist"]):
                    notes.append("all-caps word in hook: {!r}".format(bare))
    return notes


def cmd_qa(paths):
    rules = load_json(RULES_PATH)
    if not paths:
        if not os.path.isdir(OUT_DIR):
            sys.exit("no out/ directory; run `python3 creative_loop.py generate` first")
        paths = sorted(
            os.path.join(OUT_DIR, n)
            for n in os.listdir(OUT_DIR)
            if n.startswith("brief-") and n.endswith(".md")
        )
        if not paths:
            sys.exit("no briefs in out/; run `python3 creative_loop.py generate` first")

    log = load_json(LOG_PATH) if os.path.exists(LOG_PATH) else None
    failures = 0
    for path in paths:
        with open(path, encoding="utf-8") as f:
            text = f.read()
        notes = qa_brief(text, rules)
        ok = not notes
        failures += 0 if ok else 1
        angle_id = os.path.basename(path)[len("brief-"):-len(".md")]
        print("{} {}".format("PASS" if ok else "FAIL", angle_id))
        for n in notes:
            print("     - {}".format(n))
        if log:
            for entry in log["entries"]:
                if entry["angle_id"] == angle_id:
                    entry["brand_qa"] = {
                        "pass": ok,
                        "notes": notes if notes else "all brand-rules checks passed",
                    }
    if log:
        with open(LOG_PATH, "w", encoding="utf-8") as f:
            json.dump(log, f, indent=2)
            f.write("\n")
        print("updated {}".format(os.path.relpath(LOG_PATH, HERE)))
    print("{} of {} briefs passed".format(len(paths) - failures, len(paths)))
    if failures:
        sys.exit(1)


# ---------------------------------------------------------------- scoreboard


def cmd_scoreboard():
    if not os.path.exists(LOG_PATH):
        sys.exit("no creative log; run `python3 creative_loop.py generate` first")
    log = load_json(LOG_PATH)

    def cell(v):
        if v is None:
            return "null"
        if isinstance(v, dict):
            return "null" if v.get("pass") is None else ("pass" if v["pass"] else "fail")
        return str(v)

    header = ("angle_id", "platform", "qa", "status", "impressions",
              "signal_value", "skan_postbacks", "cost")
    rows = [header]
    for e in log["entries"]:
        r = e["results"]
        rows.append((
            e["angle_id"], e["platform"], cell(e["brand_qa"]), e["status"],
            cell(r["impressions"]), cell(r["signal_value"]),
            cell(r["skan_postbacks"]), cell(r["campaign_level_cost"]),
        ))
    widths = [max(len(row[i]) for row in rows) for i in range(len(header))]
    for i, row in enumerate(rows):
        print("  ".join(c.ljust(w) for c, w in zip(row, widths)).rstrip())
        if i == 0:
            print("  ".join("-" * w for w in widths))
    print()
    print("no data: nothing has been published.")
    print("Every result field is null because this system has never run against a real account.")


# ---------------------------------------------------------------- publish


class PublishAdapter:
    """Deliberately disabled. Exists so the seam is visible and testable."""

    def publish(self, entry):
        raise NotImplementedError(
            "Publishing is disabled by design and is not implemented anywhere in this repo. "
            "Before any adapter may be written, the FOUNDER must decide, in writing: "
            "(1) that a real monthly budget exists, "
            "(2) which platform account to create and fund, and "
            "(3) that the no-spend / no-publish guardrail is being lifted. "
            "No credentials are read anywhere in this code, and dry-run is the only implemented mode."
        )


def cmd_publish():
    try:
        PublishAdapter().publish(None)
    except NotImplementedError as e:
        print("publish refused: {}".format(e))
        sys.exit(2)


# ---------------------------------------------------------------- main


def main(argv):
    cmd = argv[1] if len(argv) > 1 else ""
    if cmd == "generate":
        cmd_generate()
    elif cmd == "qa":
        cmd_qa(argv[2:])
    elif cmd == "scoreboard":
        cmd_scoreboard()
    elif cmd == "publish":
        cmd_publish()
    else:
        sys.exit("usage: python3 creative_loop.py generate|qa|scoreboard  (publish exists but refuses, by design)")


if __name__ == "__main__":
    main(sys.argv)
